ASP-Task3/ASP-Task3/Entities/Product.cs
namespace ASP_Task3.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Discount { get; set; }
        public int Price { get; set; }
        public string ImageLink { get; set; }

    }
}

ASP-Task3/ASP-Task3/Models/ErrorViewModel.cs
using System;

namespace ASP_Task3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP-Task3/ASP-Task3/Models/ProductAddViewModel.cs
using ASP_Task3.Entities;

namespace ASP_Task3.Models
{
    public class ProductAddViewModel
    {
        public Product Product { get; set; }
    }
}

ASP-Task3/ASP-Task3/Models/ProductListViewModel.cs
using ASP_Task3.Entities;
using System.Collections.Generic;

namespace ASP_Task3.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
    }
}

ASP-Task3/ASP-Task3/Controllers/HomeController.cs
using ASP_Task3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace ASP_Task3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP-Task3/ASP-Task3/Controllers/ProductController.cs
using ASP_Task3.Data;
using ASP_Task3.Entities;
using ASP_Task3.Models;
using ASP_Task3.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace ASP_Task3.Controllers
{
    public class ProductController : Controller
    {

        private readonly ProductDbContext _context;
        private readonly IProductService _productService;

        public ProductController(IProductService productService, ProductDbContext context)
        {
            _productService = productService;
            _context = context;
        }

        public async Task<IActionResult> Index(string key = "")
        {
            var items = await _productService.GetAllByKey(key);
            return Ok(items);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var vm = new ProductAddViewModel
            {
                Product = new Product()
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> Add(ProductAddViewModel vm)
        {
            if (ModelState.IsValid)
            {
                _context.Products.Add(vm.Product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return View(vm);
            }
        }


        [HttpGet]

        public async Task<ActionResult> Update(int id)
        {
            var product = _context.Products.SingleOrDefault(e => e.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            var vm = new ProductAddViewModel
            {
                Product = product
            };
            return View(vm);
        }


        [HttpPost]
        public async Task<ActionResult> Update(ProductAddViewModel vm)
        {
            if (ModelState.IsValid)
            {
                _context.Products.Update(vm.Product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return View(vm);
            }
        }


        [HttpGet]

        public async Task<ActionResult> Delete(int id)
        {
            var item = _context.Products.SingleOrDefault(e => e.Id == id);
            if (item != null)
            {
                _context.Products.Remove(item);
            }

            return RedirectToAction("Index");
        }


    }
}

ASP-Task3/ASP-Task3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP-Task3/ASP-Task3/Views/Product/Add.cshtml
@model ProductAddViewModel

<section>
    <form asp-controller="Product" asp-action="Add" asp-route-id="@Model.Product.Id">
        <section>
            <label asp-for="Product.Name"></label>
            <input asp-for="Product.Name"/>
        </section>

        <section>
            <label asp-for="Product.Description"></label>
            <input asp-for="Product.Description" />
        </section>

        <section>
            <label asp-for="Product.ImageLink"></label>
            <input asp-for="Product.ImageLink" />
        </section>

        <section>
            <label asp-for="Product.Price"></label>
            <input asp-for="Product.Price" />
        </section>

        <button type="submit" >Add Product</button>
</form>
</section>

ASP-Task3/ASP-Task3/Views/Product/Product.cshtml
@model ProductListViewModel


<section>
    @foreach (var item in Model.Products)
    {
        <section>
            <h2>Id : @item.Id</h2>
            <h2>Name : @item.Name</h2>
            <h2>Price : @item.Price</h2>
            <h2>Discount : @item.Discount</h2>
            <h2>Description : @item.Description</h2>
            <img src="@item.ImageLink"/>
            <hr />
            <button asp-controller="Product" asp-action="Delete" asp-route-id="@item.Id">Delete</button>
            <button asp-controller="Product" asp-action="Add" asp-route-id="@item.Id">Add</button>
            <button asp-controller="Product" asp-action="Edit" asp-route-id="@item.Id">Edit</button>
            </section>
    }
</section>

ASP-Task3/ASP-Task3/Views/Product/Update.cshtml
@model ProductAddViewModel

<section>
    <form asp-controller="Product" asp-action="Edit" asp-route-id="@Model.Product.Id">
        <section>
            <label asp-for="Product.Name"></label>
            <input asp-for="Product.Name" />
        </section>

        <section>
            <label asp-for="Product.Description"></label>
            <input asp-for="Product.Description" />
        </section>

        <section>
            <label asp-for="Product.ImageLink"></label>
            <input asp-for="Product.ImageLink" />
        </section>

        <section>
            <label asp-for="Product.Price"></label>
            <input asp-for="Product.Price" />
        </section>

        <button type="submit">Add Product</button>
    </form>
</section>

ASP-Task3/ASP-Task3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_Task3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_Task3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP_Task3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>