ASP-Task4/ASP-Task4/Entities/Category.cs
namespace ASP_Task4.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string? Title { get; set; }
    }
}

ASP-Task4/ASP-Task4/Entities/Product.cs
namespace ASP_Task4.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public decimal Price { get; set; }
    }
}

ASP-Task4/ASP-Task4/Models/CategoryListViewModel.cs
namespace ASP_Task4.Models
{
    public class CategoryListViewModel
    {
        public IQueryable<CategoryViewModel>? Categories { get; set; }
    }
}

ASP-Task4/ASP-Task4/Models/CategoryViewModel.cs
namespace ASP_Task4.Models
{
    public class CategoryViewModel
    {
        public string? Title { get; set; }

    }
}

ASP-Task4/ASP-Task4/Models/ErrorViewModel.cs
namespace ASP_Task4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP-Task4/ASP-Task4/Models/ProductCategoryListViewModel.cs
namespace ASP_Task4.Models
{
    public class ProductCategoryListViewModel
    {
        public IQueryable<ProductViewModel>? Products { get; set; }
        public IQueryable<CategoryViewModel>? Categories { get; set; }
    }
}

ASP-Task4/ASP-Task4/Models/ProductViewModel.cs
namespace ASP_Task4.Models
{
    public class ProductViewModel
    {
        public string? Name { get; set; }
        public decimal Price { get; set; }
    }
}

ASP-Task4/ASP-Task4/Controllers/HomeController.cs
using ASP_Task4.Data;
using ASP_Task4.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP_Task4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ProductDbContext _context;

        public HomeController(ProductDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var products = _context.Products.Select(p => new ProductViewModel { Name = p.Name, Price = p.Price });
            var categories = _context.Categories.Select(c => new CategoryViewModel { Title = c.Title });

            var vm = new ProductCategoryListViewModel
            {
                Categories = categories,
                Products = products
            };
            return View(vm);

        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ASP-Task4/ASP-Task4/Pages/Product/Index.cshtml.cs
using ASP_Task4.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP_Task4.Pages.Product
{
    public class IndexModel : PageModel
    {
        private readonly ProductDbContext _context;

        public IndexModel(ProductDbContext context)
        {
            _context = context;
        }

        public List<Entities.Product> Products { get; set; }

        public string Info { get; set; }

        [BindProperty]
        public Entities.Product NewProduct { get; set; }

        [BindProperty]
        public Entities.Product EditProduct { get; set; }

        public void OnGet(string info = "")
        {
            LoadProducts();
            Info = info;
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                LoadProducts();
                return Page();
            }

            if (NewProduct.Id == 0)
            {
                _context.Products.Add(NewProduct);
                Info = $"{NewProduct.Name} added successfully";
            }

            _context.SaveChanges();
            return RedirectToPage("Index", new { info = Info });
        }

        public IActionResult OnPostEdit(int id)
        {
            EditProduct = _context.Products.Find(id);
            if (EditProduct != null)
            {
                LoadProducts();
                return Page();
            }

            return RedirectToPage("Index", new { info = "Product not found" });
        }

        public IActionResult OnPostUpdate()
        {
            if (!ModelState.IsValid)
            {
                LoadProducts();
                return Page();
            }

            var modifyProduct = _context.Products.Find(EditProduct.Id);
            if (modifyProduct != null)
            {
                modifyProduct.Name = EditProduct.Name;
                modifyProduct.Price = EditProduct.Price;
                _context.SaveChanges();
                Info = $"{EditProduct.Name} updated successfully";
            }

            return RedirectToPage("Index", new { info = Info });
        }

        public IActionResult OnPostDelete(int id)
        {
            var product = _context.Products.Find(id);
            if (product != null)
            {
                _context.Products.Remove(product);
                _context.SaveChanges();
                Info = $"{product.Name} deleted successfully";
            }
            return RedirectToPage("Index", new { info = Info });
        }

        private void LoadProducts()
        {
            Products = _context.Products.ToList();
        }
    }
}

ASP-Task4/ASP-Task4/ViewComponents/CategoryListViewComponent.cs
using ASP_Task4.Data;
using ASP_Task4.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace ASP_Task4.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ProductDbContext _context;
        public CategoryListViewComponent(ProductDbContext context)
        {
            _context = context;
        }

        public ViewViewComponentResult Invoke()
        {
            var categories = _context.Categories.Select(c => new CategoryViewModel { Title = c.Title });
            return View(
                new CategoryListViewModel
                {
                    Categories = categories
                });
        }


    }
}

ASP-Task4/ASP-Task4/Pages/Product/Index.cshtml
@page
@model ASP_Task4.Pages.Product.IndexModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td scope="row">@item.Id</td>
                <td scope="row">@item.Name</td>
                <td scope="row">@item.Price$</td>
                <td scope="row">
                    <form method="post" asp-page-handler="Edit">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button type="submit" class="btn btn-outline-warning">Edit</button>
                    </form>
                </td>
                <td>
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<form class="col-5" method="post">
    <h2 class="h2">Add Form</h2>
    <div class="mb-3">
        <label class="form-label">Product Name</label>
        <input asp-for="NewProduct.Name" class="form-control" />
    </div>
    <div class="mb-3">
        <label class="form-label">Product Price</label>
        <input asp-for="NewProduct.Price" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Add New Product</button>
</form>

<hr />

<form class="col-5" method="post" asp-page-handler="Update">
    <h2 class="h2">Edit Form</h2>
    <input type="hidden" asp-for="EditProduct.Id" />
    <div class="mb-3">
        <label class="form-label">Edit Name</label>
        <input asp-for="EditProduct.Name" class="form-control" />
    </div>
    <div class="mb-3">
        <label class="form-label">Edit Price</label>
        <input asp-for="EditProduct.Price" class="form-control" />
    </div>
    <button type="submit" class="btn btn-outline-secondary">Save Changes</button>
</form>

ASP-Task4/ASP-Task4/Views/Home/Index.cshtml
@model ProductCategoryListViewModel

<h1>Products</h1>
@if(Model.Products != null)
{
    @foreach (var item in Model.Products)
    {
        <h2>Name : @item.Name</h2>
        <h2>Price : @item.Price</h2>
    }
}
<hr />
@if(Model.Categories != null)
{
    @foreach (var item in Model.Categories)
    {
        <h2>Title : @item.Title</h2>
    }
}

ASP-Task4/ASP-Task4/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel

<section>
    @if (Model.Categories != null)
    {
        <h1>Categories</h1>
        <ul class="list-group">
            @foreach (var item in Model.Categories)
            {
                <li class="list-group-item">@item.Title</li>
            }
        </ul>
    }
</section>

ASP-Task4/ASP-Task4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_Task4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_Task4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_Task4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                @await Component.InvokeAsync("CategoryList")
            </div >
            <div class="col-md-8">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP_Task4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>